---
# tasks file for install_vsftpd

#install ftp server
- name: install vsftpd
  yum:
    name: vsftpd
    state: present

#create directoris
- name: create directory for anon users with read permissions
  file:
    path: '{{vsftpd_anon_dir_read}}'
    owner: root
    group: root
    state: directory
    setype: '{{vsftpd_setype_for_read}}'

- name: create directory for anon users with write permissions
  file:
    path: '{{vsftpd_anon_dir_write}}'
    owner: ftp
    group: ftp
    mode: 0755
    state: directory
    setype: '{{vsftpd_setype_for_write}}'


#create config from template
- name: create vsftpd.conf
  template:
    src: vsftpd.conf.j2
    dest: /etc/vsftpd/vsftpd.conf
  notify:
    - restart vsftpd

#check/run vsftpd
- name: check/run vsftpd
  service:
    name: vsftpd
    state: started
    enabled: yes

- name: config firewalld
  import_tasks: 'firewalld.yaml'

- name: edit selinux permissions
  import_tasks: 'selinux.yaml'
