---
- name: task_1-2
  hosts: node1.example.com

  tasks:
  - name: remove apache package
    yum:
     name: httpd
     state: absent

  - name: delete index.html
    file:
     path: /var/www/html/index.html
     state: absent

  - name: close http access
    firewalld:
     service: http
     permanent: true
     state: disabled
    notify:
    - restart firewalld

  handlers:
    - name: restart firewalld
      service:
       name: firewalld
       state: restarted
...
