---
# handlers file for install_vsftpd
- name: restart firewalld
  service:
    name: firewalld
    state: restarted

- name: restart vsftpd
  service:
    name: vsftpd
    state: restarted
