---
#install apache
- name: install apache
  yum:
    name: httpd
    state: present
#get apache version
- name: get apache version
  command: httpd -v
  changed_when: false
  register: _apache_version

- name: set facts about apache version
  set_fact:
    apache_version: '{{_apache_version.stdout.split()[2].split("/")[1]}}'

#creatce index.html from template
- name: create index.html
  template:
    src: index.j2
    dest: /var/www/html/index.html

#run apache
- name: run apache package
  service:
    name: httpd
    state: started
    enabled: yes

#run and configure firewalld
- name: run firewalld
  service:
    name: firewalld
    state: started
    enabled: yes

- name: open http access
  firewalld:
    service: http
    permanent: true
    state: enabled
  notify:
    - restart firewalld
